version: '2'
services:
  httpserve:
    build:
      context: client
      dockerfile: httpserve.dock
    image: httpserve 
    container_name: httpserve-container
    ports:
      - "8080:8080"
    volumes:
      - ./client/public:/app
  webpack:
    build:
      context: client
      dockerfile: webpack.dock
    image: webpack
    container_name: webpack-container
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
      - ./shared:/app/src/shared
      - ./game:/app/src/game
      - /app/node_modules
  signalling:
    build:
      context: signalling
      dockerfile: signalling.dock
    image: signalling
    container_name: signalling-container
    ports:
      - "9000:9000"
    volumes:
      - ./signalling:/app
      - /app/node_modules
  stun:
    build:
      context: stun
      dockerfile: stun.dock
    image: stun
    container_name: stun-container
    network_mode: host
    ports:
      - "3478:3478"
